version: "3.8"

services:
  server:
    container_name: go_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - DB_HOST=host.docker.internal
      - REDIS_HOST=host.docker.internal
    restart: on-failure
