version: "3.3"

services:
  server:
    container_name: pichub.api
    build:
      context: .
      dockerfile: Dockerfile
      network: docker20
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - DB_HOST=host.docker.internal
      - REDIS_HOST=host.docker.internal
    restart: on-failure
    dns:
      - 8.8.8.8
      - 114.114.114.114
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - docker20

networks:
  docker20:
    external: true